// The words a passphrase is built from.
//
// ⚠ **A passphrase here is said out loud by one person and typed by another.**
// ⚠ **So the list is chosen for being heard correctly, not for being large.**
//   ⚠ **`docs/adr/0007-say-a-passphrase-in-four-words-chosen-to-be-heard-correctly.md` carries the decision
//   ⚠ and what was rejected.**
//
// ⚠ **Every property below is asserted by `test/passphrase.test.ts`.**
//   ⚠ **Adding a word without checking those properties breaks the entropy claim, the uniform
//   ⚠ selection, or both** — ⚠ **and none of that is visible by reading the list.**
//
//     the count is a power of two   ⚠ so a masked random byte selects uniformly, with no bias
//     no two words differ by one edit ⚠ so a mishearing does not produce another valid word
//     every word is at least 5 letters ⚠ short words collide constantly; this is why
//     lowercase ASCII only          ⚠ no IME needed to type it
//     no ambiguous long vowel        ⚠ "hodou" / "hodō" / "hodoo" would be three spellings
//
// ⚠ **The words are romanised Japanese, in Hepburn.**
//   ⚠ **They are tokens, not meanings** — ⚠ nothing reads them as words.

/**
 * ⚠ **Bits contributed by one word.** ⚠ **The list length must be exactly `2 ** BITS_PER_WORD`**,
 * ⚠ **and a test asserts it.** ⚠ **A list that is not a power of two cannot be selected from with
 * a masked byte without introducing modulo bias.**
 */
export const BITS_PER_WORD = 7;

/** ⚠ **Sorted, so a duplicate is visible in a diff.** */
export const WORDS: readonly string[] = [
  "akikaze",
  "amagumo",
  "amaoto",
  "arashi",
  "asagiri",
  "asahi",
  "ashiato",
  "ayame",
  "botan",
  "chawan",
  "chikara",
  "chochin",
  "daikon",
  "fukuro",
  "futon",
  "fuyuzora",
  "hachi",
  "hanabi",
  "hanabira",
  "haori",
  "harukaze",
  "hasami",
  "hashira",
  "hatsuyuki",
  "hayashi",
  "hibiki",
  "hikari",
  "hinata",
  "hiroba",
  "hitsuji",
  "hoshi",
  "hoshizora",
  "hotaru",
  "ichigo",
  "ikada",
  "inazuma",
  "izumi",
  "jinja",
  "kaban",
  "kabocha",
  "kabuto",
  "kaeru",
  "kagami",
  "kaidan",
  "kaminari",
  "karasu",
  "kareha",
  "karuta",
  "kasumi",
  "katana",
  "kawagishi",
  "kimono",
  "kinoko",
  "kitsune",
  "kokoro",
  "konbu",
  "konoha",
  "kozue",
  "kushi",
  "kutsu",
  "makura",
  "matsu",
  "matsuri",
  "michi",
  "midori",
  "mikan",
  "minato",
  "momiji",
  "morikage",
  "murasaki",
  "musubi",
  "nashi",
  "natsukusa",
  "natto",
  "negai",
  "nezumi",
  "ninjin",
  "nodoka",
  "nohara",
  "ochiba",
  "odori",
  "origami",
  "ringo",
  "saifu",
  "sakana",
  "sazanami",
  "shamisen",
  "shiitake",
  "shika",
  "shimo",
  "shinme",
  "shiokaze",
  "shirabe",
  "shizuka",
  "suzume",
  "taiko",
  "tamago",
  "tanuki",
  "tatami",
  "tenugui",
  "tetsu",
  "tobira",
  "tokei",
  "tomato",
  "torii",
  "tsuba",
  "tsubaki",
  "tsubame",
  "tsubomi",
  "tsuchi",
  "tsuki",
  "tsukiyo",
  "tsukue",
  "tsuru",
  "tsutsumi",
  "umeboshi",
  "umibe",
  "usagi",
  "wakaba",
  "wakame",
  "waraji",
  "yagura",
  "yakan",
  "yamabiko",
  "yamamichi",
  "yanagi",
  "yasai",
  "yoroi",
] as const;
